/**
 * MSW server for Node/test environments.
 *
 * Hand-maintained (NOT regenerated by `generate:mocks`, which only rewrites
 * `handlers.ts`). The override handlers are composed BEFORE the auto-generated
 * handlers so they take precedence — MSW uses the first matching handler. See
 * `handler-overrides.ts` for why those overrides exist.
 */
import {setupServer} from 'msw/node';

import {overrideHandlers} from './handler-overrides.js';
import {handlers} from './handlers.js';

export const server = setupServer(...overrideHandlers, ...handlers);
